// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Sodium")>]
[<assembly: AssemblyProductAttribute("FSharp.Sodium")>]
[<assembly: AssemblyDescriptionAttribute("Sodium - Functional Reactive Programming (FRP) library for .NET written in F#.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Sodium"
    let [<Literal>] AssemblyProduct = "FSharp.Sodium"
    let [<Literal>] AssemblyDescription = "Sodium - Functional Reactive Programming (FRP) library for .NET written in F#."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
